name: Auto Labeler

on:
  pull_request_target:
    types: [opened]
  # issue labeling 을 위한 설정
  # issues:
  #   types: [opened, edited, milestoned]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
