name: PR Labeler
on:
  pull_request_target:
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read|write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auto Label PR
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          LOG_LEVEL: 'debug'
